### ISSUE TITLE
Error in startup log

### ISSUE THREAD

**Issue by talapadi** [chimple/maui#1025]
I/flutter (22972): user: User{id: 68ce68b0-5d73-41c1-
I/flutter (22972): ══╡ EXCEPTION CAUGHT BY SCHEDULER LIBRARY ╞═════════════════════════════════════════════════════════
I/flutter (22972): The following NoSuchMethodError was thrown during a scheduler callback:
I/flutter (22972): The getter 'isLooping' was called on null.
I/flutter (22972): Receiver: null
I/flutter (22972): Tried calling: isLooping
I/flutter (22972): 
I/flutter (22972): When the exception was thrown, this was the stack:
I/flutter (22972): #0      Object.noSuchMethod (dart:core/runtime/libobject_patch.dart:50:5)
I/flutter (22972): #1      NimaActorRenderObject.beginFrame (package:nima/nima_actor.dart:264:23)
I/flutter (22972): #2      _WidgetsFlutterBinding&BindingBase&GestureBinding&ServicesBinding&SchedulerBinding._invokeFrameCallback (package:flutter/src/scheduler/binding.dart:990:15)
I/flutter (22972): #3      _WidgetsFlutterBinding&BindingBase&GestureBinding&ServicesBinding&SchedulerBinding.handleBeginFrame.<anonymous closure> (package:flutter/src/scheduler/binding.dart:906:11)
I/flutter (22972): #4      __InternalLinkedHashMap&_HashVMBase&MapMixin&_LinkedHashMapMixin.forEach (dart:collection/runtime/libcompact_hash.dart:370:8)
I/flutter (22972): #5      _WidgetsFlutterBinding&BindingBase&GestureBinding&ServicesBinding&SchedulerBinding.handleBeginFrame (package:flutter/src/scheduler/binding.dart:904:17)
I/flutter (22972): #6      _WidgetsFlutterBinding&BindingBase&GestureBinding&ServicesBinding&SchedulerBinding._handleBeginFrame (package:flutter/src/scheduler/binding.dart:834:5)
I/flutter (22972): #7      _invoke1 (dart:ui/hooks.dart:165:13)
I/flutter (22972): #8      _beginFrame (dart:ui/hooks.dart:135:3)
I/flutter (22972): 
I/flutter (22972): 
I/flutter (22972): This exception was thrown in the context of a scheduler callback. When the scheduler callback was
I/flutter (22972): _registered_ (as opposed to when the exception was thrown), this was the stack:
I/flutter (22972): #0      new _FrameCallbackEntry.<anonymous closure> (package:flutter/src/scheduler/binding.dart:109:33)
I/flutter (22972): #1      new _FrameCallbackEntry (package:flutter/src/scheduler/binding.dart:112:6)
I/flutter (22972): #2      _WidgetsFlutterBinding&BindingBase&GestureBinding&ServicesBinding&SchedulerBinding.scheduleFrameCallback (package:flutter/src/scheduler/binding.dart:426:49)
I/flutter (22972): #3      NimaActorRenderObject.beginFrame (package:nima/nima_actor.dart:308:30)
I/flutter (22972): #4      _WidgetsFlutterBinding&BindingBase&GestureBinding&ServicesBinding&SchedulerBinding._invokeFrameCallback (package:flutter/src/scheduler/binding.dart:990:15)
I/flutter (22972): #5      _WidgetsFlutterBinding&BindingBase&GestureBinding&ServicesBinding&SchedulerBinding.handleBeginFrame.<anonymous closure> (package:flutter/src/scheduler/binding.dart:906:11)
I/flutter (22972): #6      __InternalLinkedHashMap&_HashVMBase&MapMixin&_LinkedHashMapMixin.forEach (dart:collection/runtime/libcompact_hash.dart:370:8)
I/flutter (22972): #7      _WidgetsFlutterBinding&BindingBase&GestureBinding&ServicesBinding&SchedulerBinding.handleBeginFrame (package:flutter/src/scheduler/binding.dart:904:17)
I/flutter (22972): #8      _WidgetsFlutterBinding&BindingBase&GestureBinding&ServicesBinding&SchedulerBinding._handleBeginFrame (package:flutter/src/scheduler/binding.dart:834:5)
I/flutter (22972): #9      _invoke1 (dart:ui/hooks.dart:165:13)
I/flutter (22972): #10     _beginFrame (dart:ui/hooks.dart:135:3)
I/flutter (22972): ════════════════════════════════════════════════════════════════════════════════════════════════════
I/flutter (22972): Another exception was thrown: setState() called after dispose(): WelcomeScreenState#31320(lifecycle state: defunct, not mounted)
Syncing files to device Android SDK built for x86...
I/flutter (22972): MediaQueryData(size: Size(411.4, 683.4), devicePixelRatio: 2.6, textScaleFactor: 1.0, padding: EdgeInsets.zero, viewInsets: EdgeInsets.zero, alwaysUse24HourFormat: false, accessibleNavigation: falsedisableAnimations: falseinvertColors: falseboldText: false)
I/flutter (22972): MediaQueryData(size: Size(411.4, 683.4), devicePixelRatio: 2.6, textScaleFactor: 1.0, padding: EdgeInsets.zero, viewInsets: EdgeInsets.zero, alwaysUse24HourFormat: false, accessibleNavigation: falsedisableAnimations: falseinvertColors: falseboldText: false)
I/flutter (22972): path: /storage/emulated/0
E/flutter (22972): [ERROR:flutter/shell/common/shell.cc(184)] Dart Error: Unhandled exception:
E/flutter (22972): NoSuchMethodError: The method 'ancestorStateOfType' was called on null.
E/flutter (22972): Receiver: null
E/flutter (22972): Tried calling: ancestorStateOfType(Instance of 'TypeMatcher<NavigatorState>')
E/flutter (22972): #0      Object.noSuchMethod (dart:core/runtime/libobject_patch.dart:50:5)
E/flutter (22972): #1      Navigator.of (package:flutter/src/widgets/navigator.dart:1288:19)
E/flutter (22972): #2      WelcomeScreenState.initState.<anonymous closure> (package:maui/screens/welcome_screen.dart:18:17)
E/flutter (22972): #3      new Future.delayed.<anonymous closure> (dart:async/future.dart:316:39)
E/flutter (22972): #4      Timer._createTimer.<anonymous closure> (dart:async/runtime/libtimer_patch.dart:21:15)
E/flutter (22972): #5      _Timer._runTimers (dart:isolate/runtime/libtimer_impl.dart:382:19)
E/flutter (22972): #6      _Timer._handleMessage (dart:isolate/runtime/libtimer_impl.dart:416:5)
E/flutter (22972): #7      _RawReceivePortImpl._handleMessage (dart:isolate/runtime/libisolate_patch.dart:171:12)

**Comment by talapadi** [comment]
Should be fixed
